// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ip_whitelist

import (
	"core-ticket/base/helpers/wire_helper"
	"core-ticket/modules/ip_whitelist/ip_whitelist_repository"
	"core-ticket/modules/ip_whitelist/ip_whitelist_service"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeIpWhitelistService(db map[string]*sqlx.DB) (ip_whitelist_service.IpWhitelistService, error) {
	sqlxDB := wire_helper.ProviderDBMain(db)
	ipWhitelistRepository := ip_whitelist_repository.NewIpWhitelistRepository(sqlxDB)
	ipWhitelistService := ip_whitelist_service.NewIpWhitelistService(ipWhitelistRepository)
	return ipWhitelistService, nil
}

// wire.go:

var ProviderSet = wire.NewSet(ip_whitelist_repository.NewIpWhitelistRepository)
