// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package return_ticket

import (
	"core-ticket/modules/return_ticket/return_ticket_handler"
	"core-ticket/modules/return_ticket/return_ticket_repository"
	"core-ticket/modules/return_ticket/return_ticket_service"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeReturnTicketService(db map[string]*sqlx.DB) return_ticket_service.ReturnTicketService {
	returnTicketRepository := return_ticket_repository.NewReturnTicketRepository(db)
	returnTicketService := return_ticket_service.NewReturnTicketService(returnTicketRepository)
	return returnTicketService
}

func InitializeReturnTicketHandler(db map[string]*sqlx.DB) return_ticket_handler.ReturnTicketHandler {
	returnTicketService := InitializeReturnTicketService(db)
	returnTicketHandler := return_ticket_handler.NewReturnTicketHandler(returnTicketService)
	return returnTicketHandler
}
