// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package healthcheck

import (
	"core-ticket/modules/common/healthcheck/healthcheck_handler"
	"core-ticket/modules/common/healthcheck/healthcheck_service"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeHealthCheckHandler(dbConnections map[string]*sqlx.DB) (healthcheck_handler.HealthCheckHandler, error) {
	healthCheckService := healthcheck_service.NewHealthCheckService(dbConnections)
	healthCheckHandler := healthcheck_handler.NewHealthCheckHandler(healthCheckService)
	return healthCheckHandler, nil
}
